apiVersion: apps/v1
kind: Deployment
metadata:
  name: "go-server"
  labels:
    app: "go-server"
spec:
  selector:
    matchLabels:
      app: "go-server"
  replicas: 2
  template:
    metadata:
      labels:
        app: "go-server"
    spec:
      containers:
      - name: "go-server"
        image: "becardine/hello-go:latest"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: "go-server-config"
            volumesMounts:
            - name: "go-server-config"
              mountPath: "/etc/config"
        # env:
        # - name: "PORT"
        #   valueFrom:
        #     configMapKeyRef:
        #       name: "go-server-config"
        #       key: "PORT"
        # - name: "MESSAGE"
        #   valueFrom:
        #     configMapKeyRef:
        #       name: "go-server-config"
        #       key: "MESSAGE"
        # - name: "VERSION"
        #   valueFrom:
        #     configMapKeyRef:
        #       name: "go-server-config"
        #       key: "VERSION"
        volumes:
        - name: "go-server-config"
          configMap:
            name: "go-server-config"
            items:
            - key: peoples
              path: peoples.json

